**PROBELM 1**

Generating an array of size (5,4) with random integers from 1 to 50

In [ ]:
import numpy as np
arr = np.random.randint(1, 51, size=(5,4))
arr

array([[45, 30, 33, 27],
       [42, 11, 15, 11],
       [10, 46, 32, 44],
       [24, 40, 33, 47],
       [ 2, 27, 29, 27]])

Returns maximum of the row for all rows

In [ ]:
for i in range(5):
  max = 0
  for j in range(4):
    if arr[i][j] > max:
      max = arr[i][j]
  print(max)

47
45
39
36
46


Return an array of elements less than or equal to mean of elements of given array


In [ ]:
arr.mean()
brr = arr[arr <= arr.mean()]
brr

array([ 8, 26, 18, 16,  4, 17, 20, 14, 18, 18])

return boundary elements of numpy array

In [ ]:
def numpy_boundary_traversal(matrix):
  rows, cols = matrix.shape
  list = []
  for i in range(cols):
    list.append(int(matrix[0][i]))
  for i in range(1, rows):
    list.append(int(matrix[i][cols-1]))
  for i in range(cols-2, -1, -1):
    list.append(int(matrix[rows-1][i]))
  for i in range(rows-2, 0, -1):
    list.append(int(matrix[i][0]))
  return list

print(numpy_boundary_traversal(arr))


[45, 30, 33, 27, 11, 44, 47, 27, 29, 27, 2, 24, 10, 42]


**PROBLEM 2**

In [ ]:
array = np.random.uniform(low=0.0, high=10.0, size=20)
print(array)

[4.26939935 6.5710378  5.06142977 9.41021867 3.62064332 8.22038675
 3.32356964 0.73788982 8.38232809 0.70772623 6.02131626 6.27869315
 4.43564738 7.450164   5.56239837 7.11154803 3.34906963 3.57635344
 5.99744158 6.53409428]


In [ ]:
np.round(array, 2)

array([4.27, 6.57, 5.06, 9.41, 3.62, 8.22, 3.32, 0.74, 8.38, 0.71, 6.02,
       6.28, 4.44, 7.45, 5.56, 7.11, 3.35, 3.58, 6.  , 6.53])

In [ ]:
np.min(array), np.max(array), np.median(array)

(np.float64(0.7077262311185262),
 np.float64(9.410218667231328),
 np.float64(5.7799199749024694))

In [ ]:
for i in range(len(array)):
  if array[i] < 5:
    array[i] = array[i]**2

array

array([18.22777084,  6.5710378 ,  5.06142977,  9.41021867, 13.10905807,
        8.22038675, 11.04611518,  0.54448139,  8.38232809,  0.50087642,
        6.02131626,  6.27869315, 19.67496771,  7.450164  ,  5.56239837,
        7.11154803, 11.21626736, 12.79030394,  5.99744158,  6.53409428])

In [ ]:
def numpy_alternate_sort(array):
  brr = array.copy()
  crr = []
  for i in range(int(len(array)/2)):
    max = np.max(brr)
    min = np.min(brr)
    crr = np.append(crr, min)
    crr = np.append(crr, max)
    brr = np.delete(brr, np.where(brr == max))
    brr = np.delete(brr, np.where(brr == min))
  return crr

print(numpy_alternate_sort(array))


[ 0.50087642 19.67496771  0.54448139 18.22777084  5.06142977 13.10905807
  5.56239837 12.79030394  5.99744158 11.21626736  6.02131626 11.04611518
  6.27869315  9.41021867  6.53409428  8.38232809  6.5710378   8.22038675
  7.11154803  7.450164  ]


**Problem 3**

In [1]:
import pandas as pd
import numpy as np


names = ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack']
subjects = ['Math', 'Science', 'Math', 'English', 'Science', 'English', 'Math', 'Science', 'English', 'Math']
scores = np.random.randint(50, 101, size=10)

df = pd.DataFrame({
    'Name': names,
    'Subject': subjects,
    'Score': scores,
    'Grade': ''
})


def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Score'].apply(assign_grade)

sorted_df = df.sort_values(by='Score', ascending=False)
print("Sorted DataFrame:\n", sorted_df)

avg_scores = df.groupby('Subject')['Score'].mean()
print("\nAverage Scores by Subject:\n", avg_scores)

def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]

passed_students = pandas_filter_pass(df)
print("\nStudents with Grade A or B:\n", passed_students)


Sorted DataFrame:
       Name  Subject  Score Grade
2  Charlie     Math     90     A
8      Ivy  English     87     B
1      Bob  Science     83     B
0    Alice     Math     83     B
6    Grace     Math     73     C
9     Jack     Math     66     D
5    Frank  English     65     D
7   Hannah  Science     65     D
4      Eve  Science     58     F
3    David  English     57     F

Average Scores by Subject:
 Subject
English    69.666667
Math       78.000000
Science    68.666667
Name: Score, dtype: float64

Students with Grade A or B:
       Name  Subject  Score Grade
0    Alice     Math     83     B
1      Bob  Science     83     B
2  Charlie     Math     90     A
8      Ivy  English     87     B


**Problem 4**

In [11]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import random

positive_reviews = [
    "Amazing movie!", "Loved it!", "Fantastic story and great acting.",
    "Best film of the year.", "Heartwarming and well directed.",
    "Superb!", "A must-watch!", "Great plot and performance.",
    "Incredible visuals.", "Wonderful experience.", "Beautifully made.",
    "Highly recommended.", "I enjoyed every moment.", "Really entertaining.",
    "Masterpiece!", "Terrific work.", "Outstanding movie.",
    "Truly inspiring.", "Powerful message.", "A cinematic gem.",
    "Top notch!", "Delightful and engaging.", "Absolutely loved it.",
    "Great character development.", "Emotionally moving.",
    "Fascinating and unique.", "Bravo!", "An instant classic.",
    "Great script and direction.", "Totally worth watching.",
    "A real joy to watch.", "Intense and beautiful.",
    "Loved the cinematography.", "Excellent pacing.",
    "A beautiful story told well.", "Gripping and emotional.",
    "Perfectly executed.", "Mind-blowing experience.",
    "One of the best!", "Oscar-worthy!", "Well acted and emotional.",
    "Great film with meaning.", "Touching and memorable.",
    "Fantastic soundtrack.", "Solid performances.",
    "Full of heart.", "Loved the ending.",
    "Fun and uplifting.", "Impressive work.", "Thought-provoking.",
    "Stunning and emotional."
]

negative_reviews = [
    "Terrible movie.", "Hated it.", "Worst film ever.",
    "Poorly directed.", "Awful acting.", "Boring and slow.",
    "Not worth watching.", "Horrible plot.", "Disappointing.",
    "Bad experience.", "Lame story.", "So predictable.",
    "Dull and uninteresting.", "Completely forgettable.",
    "Waste of time.", "Very disappointing.", "Painful to watch.",
    "Cringe-worthy.", "Full of clichés.", "The acting was bad.",
    "No chemistry between actors.", "Fell asleep halfway.",
    "Horribly written.", "Ridiculous dialogue.",
    "Confusing and messy.", "Didn't enjoy it at all.",
    "Too long and boring.", "Predictable plot.",
    "Overrated trash.", "Bad cinematography.",
    "Unrealistic and stupid.", "Lacked emotion.",
    "Soundtrack was annoying.", "Unwatchable.",
    "A total flop.", "Fails to deliver.",
    "Lifeless performance.", "Mediocre at best.",
    "Shallow and weak.", "Plot holes everywhere.",
    "So much potential wasted.", "No effort put in.",
    "Ruined a great idea.", "Just bad.",
    "Lacked direction.", "Very poorly done.",
    "Script was terrible.", "Not enjoyable.",
    "Would not recommend.", "Garbage."
]

positive_reviews = positive_reviews[:50]
negative_reviews = negative_reviews[:50]

reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50
data = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

vectorizer = CountVectorizer(max_features=500, stop_words='english')
X = vectorizer.fit_transform(data['Review'])
y = data['Sentiment']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = MultinomialNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy on test set: {accuracy:.2f}")

def predict_review_sentiment(model, vectorizer, review):
    review_vector = vectorizer.transform([review])
    prediction = model.predict(review_vector)[0]
    return prediction

test_review = "very poorly done"
print("Predicted Sentiment:", predict_review_sentiment(model, vectorizer, test_review))


Accuracy on test set: 0.50
Predicted Sentiment: negative


**Problem 5**

In [12]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score

good_feedback = [
    "Excellent product!", "Very satisfied with the quality.", "Works perfectly.",
    "Highly recommended.", "Top-notch experience.", "Superb item!", "Loved it.",
    "Five stars!", "Amazing build quality.", "Reliable and durable.",
    "Exceeded expectations.", "Value for money.", "Impressed with the performance.",
    "Fast delivery and great quality.", "Will buy again.", "Terrific support.",
    "Perfect for my needs.", "Product matches description.", "Really useful item.",
    "Great purchase!", "Nice packaging.", "Well made product.", "Everything works fine.",
    "Easy to use and effective.", "Fantastic service.",
    "Solid construction.", "Product looks premium.", "I'm very happy.",
    "Fits the purpose well.", "Good for everyday use.", "Clean design.",
    "Quick and efficient.", "Definitely worth it.", "Great price.",
    "Smooth and fast operation.", "Feels high-quality.", "No complaints at all.",
    "Will recommend to others.", "Better than expected.", "It works like a charm.",
    "Perfect condition.", "Trustworthy brand.", "Comfortable and functional.",
    "Appreciate the good service.", "Very dependable.", "Delivered on time.",
    "Positive experience overall.", "This is fantastic.", "Good job!", "Outstanding."
]

bad_feedback = [
    "Terrible product.", "Very disappointed.", "Stopped working quickly.",
    "Not worth the money.", "Low quality material.", "Didn't meet expectations.",
    "Waste of money.", "Won't buy again.", "Poor performance.",
    "Item arrived broken.", "Cheap construction.", "Very unreliable.",
    "Feels flimsy.", "Doesn't match description.", "Horrible experience.",
    "Wouldn't recommend.", "Extremely dissatisfied.", "Terrible support.",
    "Useless item.", "Arrived late.", "Bad customer service.",
    "Doesn't work at all.", "Incomplete package.", "Frustrating to use.",
    "Totally ineffective.", "Not what I expected.", "Wrong item received.",
    "Lacks important features.", "Regret buying this.", "Terrible fit.",
    "Very confusing.", "Overpriced for quality.", "Malfunctioned soon.",
    "Doesn't hold up.", "Really bad finish.", "Product is defective.",
    "Looks cheap.", "Packaging was terrible.", "Too noisy.",
    "Not comfortable to use.", "Support was unhelpful.", "Too slow.",
    "Very bad experience.", "Didn't live up to the hype.",
    "Bad smell from the product.", "Stopped working after a week.",
    "Battery life is poor.", "Really disappointing.", "Avoid this product.", "Waste."
]

good_feedback = good_feedback[:50]
bad_feedback = bad_feedback[:50]
texts = good_feedback + bad_feedback
labels = ['good'] * 50 + ['bad'] * 50
data = pd.DataFrame({'Text': texts, 'Label': labels})

vectorizer = TfidfVectorizer(max_features=300, lowercase=True, stop_words='english')
X = vectorizer.fit_transform(data['Text'])
y = data['Label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

precision = precision_score(y_test, y_pred, pos_label='good')
recall = recall_score(y_test, y_pred, pos_label='good')
f1 = f1_score(y_test, y_pred, pos_label='good')

print("Precision:", round(precision, 2))
print("Recall:", round(recall, 2))
print("F1 Score:", round(f1, 2))

def text_preprocess_vectorize(texts, vectorizer):
    """
    Takes a list of text samples and a fitted TfidfVectorizer,
    returns the vectorized feature matrix.
    """
    return vectorizer.transform(texts)

sample_texts = ["This item is amazing!", "Very poor quality."]
vectorized_samples = text_preprocess_vectorize(sample_texts, vectorizer)
predictions = model.predict(vectorized_samples)
print("\nPredictions for sample texts:", predictions)


Precision: 0.6
Recall: 0.21
F1 Score: 0.32

Predictions for sample texts: ['good' 'bad']
